/*
 * 1日Camp 卒業制作データ
 * ------------------------------------------------------------
 * 作品を追加するときは、下の WORKS に1ブロック足すだけでOK。
 *   id     : 英数字の短い名前（画像ファイル名 img/{id}.jpg と揃える）
 *   camp   : 受講した回
 *   title  : 作品名
 *   url    : 作品URL
 *   type   : "app"（Webアプリ・ツール） or "site"（ホームページ・LP）
 *   desc   : 一言紹介
 *   points : 総合点（100点満点）。無ければ「審査中」表示でランキング対象外
 *   score  : { 完成度, 実用性, 独創性 } 各10点（カードの棒グラフ用・任意）
 *   comment: 講評（任意）
 *   award  : 部門賞の名前（任意）
 * 画像が無くても表示されます（自動でタイトルカードになります）。
 */
const WORKS = [
  { id: "tochi", points: 96, camp: "7/30-31 ホリキャン", title: "トチヨム ─ 土地AI診断", url: "https://tochi-ai-shindan.pages.dev/", type: "app",
    desc: "不動産ポータルのスクショを貼るだけで、AIが「建てられる家の大きさ」と「注意点」を診断。",
    score: { 完成度: 10, 実用性: 10, 独創性: 9 },
    comment: "画像読み取り→建ぺい率・容積率の計算→レポートまで一気通貫。独自ドメイン・用語集・コラム・広告枠まで備え、もはや1日で作った“作品”ではなく“事業”。" },
  { id: "nou-denchi", points: 93, camp: "7/30-31 ホリキャン", title: "脳でんち ─ キミ！いま何%!?", url: "https://mark555limitless.github.io/nou-denchi/", type: "app", badge: "App Storeで公開中", extra: "https://apps.apple.com/jp/app/id6799632701",
    desc: "いまの判断力を、ベストな時の自分と比べて電池残量のように%表示するアプリ。",
    score: { 完成度: 10, 実用性: 8, 独創性: 10 },
    comment: "「脳の電池残量」というコンセプトの勝利。自己ベストが100%として更新される設計も秀逸で、App Storeでの公開までやり切った実行力は文句なし。" },
  { id: "dokuzetsu", points: 92, camp: "7/30-31 ホリキャン", title: "毒舌おばちゃん飯診断", url: "https://dokuzetsu-ai-meshi.pages.dev", type: "app",
    desc: "コンビニで買ったものを撮るだけ。関西のおばちゃんが6項目で採点し「あと1品」まで教えてくれる。",
    score: { 完成度: 9, 実用性: 9, 独創性: 10 },
    comment: "栄養管理を「毒舌キャラに叱られる体験」に変えた発想が見事。月額課金・特商法表記まで整えた、そのまま売れるプロダクト。" },
  { id: "shift", points: 88, camp: "8/8 オンライン", title: "爆速シフトくん", url: "https://shift-planner-pilot.vercel.app/", type: "app", award: "現場DX賞",
    desc: "障害児入所施設の月間シフトを自動作成。人員配置の必須要件チェックと警告まで出す業務ツール。",
    score: { 完成度: 9, 実用性: 10, 独創性: 7 },
    comment: "夜勤区分・資格者配置・希望休まで扱う本格派。現場の“毎月の地獄”を1日で道具に変えた、最も実務に効く一作。" },
  { id: "sento", points: 85, camp: "8/18 介護校", title: "銭湯カードコレクション", url: "https://sentocard-collection-app.vercel.app/web-prototype/index.html", type: "app", award: "偏愛クラフト賞",
    desc: "東京都の銭湯417軒のカード取得・お遍路スタンプをエリア別に管理するコレクションアプリ。",
    score: { 完成度: 8, 実用性: 8, 独創性: 9 },
    comment: "400軒超のデータと進捗表示で「制覇欲」をくすぐる。好きなものを突き詰めるとここまで作れる、という最高の見本。" },
  { id: "tanika", points: 82, camp: "8/8 オンライン", title: "タニカ建築 コーポレートサイト", url: "https://tanika-architecture.vercel.app/", type: "site", award: "ベストデザイン賞",
    desc: "広島・福山の建築設計事務所のサイト。施工写真を活かした上質なデザイン。",
    score: { 完成度: 9, 実用性: 8, 独創性: 7 },
    comment: "余白と写真の使い方がプロの設計事務所サイトそのもの。実在の自社サイトとして、そのまま差し替えられる完成度。" },
  { id: "guestvoice", points: 78, camp: "8/18 介護校", title: "Guest Voice Studio", url: "https://haposyan.github.io/guest-voice-studio/", type: "app",
    desc: "お客様の声を集めて、拠点ごとに改善を管理するWebアプリ。権限別ログイン付き。",
    score: { 完成度: 7, 実用性: 9, 独創性: 7 },
    comment: "本部・拠点・閲覧者の権限設計まで考えられており、社内導入を見据えた作り。同日に2作品を仕上げた馬力にも拍手。" },
  { id: "fukky", points: 76, camp: "8/18 対面", title: "麻酔科医のパーソナルサイト", url: "https://shinichifukky-code.github.io/", type: "site",
    desc: "経歴・理念・メディア・クリニック情報までまとめた医師のパーソナルブランディングサイト。",
    score: { 完成度: 9, 実用性: 8, 独創性: 6 },
    comment: "ボリュームと情報設計が圧倒的。「一秒を守る医療から、人生を変える医療へ」というコピーまで含めて本人の顔が見えるサイト。" },
  { id: "subsidy", points: 77, camp: "5/11 補講", title: "助成金シミュレーター", url: "https://horiemon-subsidy-simulator.vercel.app/simulator", type: "app",
    desc: "受講者数を入れるだけで、人材開発支援助成金を使った実質負担額を即座に試算。",
    score: { 完成度: 8, 実用性: 9, 独創性: 6 },
    comment: "営業現場の「いくらになるの？」に即答できる道具。試算結果をURLで共有できる気配りも実務家らしい。" },
  { id: "miyako", points: 75, camp: "8/18 対面", title: "to blue ─ 宮古島ウェイクサーフィン", url: "https://harukanakata-coder.github.io/miyako-wake-club/", type: "site",
    desc: "宮古島の中級者向けウェイクサーフィンスクールのサイト。",
    score: { 完成度: 8, 実用性: 7, 独創性: 8 },
    comment: "「ロープを、手放せ。」の一言とイラストで世界観が一瞬で伝わる。ターゲットを中級者に絞った設計も◎。" },
  { id: "mafinance", points: 73, camp: "8/18 対面", title: "M&A会計ファイナンス 新HP案", url: "https://katomikiyamikiya.github.io/ma-finance-hp-draft/", type: "site",
    desc: "買い手企業向け財務デューデリジェンスの自社HPを、AIで刷新したリニューアル案。",
    score: { 完成度: 8, 実用性: 8, 独創性: 6 },
    comment: "顧客の「買った後の後悔」から語り始める構成が秀逸。自社の課題にそのまま使った、最も“持ち帰れる”成果物。" },
  { id: "fitops", points: 72, camp: "8/18 対面", title: "FitOps", url: "https://anabuki-bonz.github.io/fitops-app-landing/", type: "site",
    desc: "個人トレーナーの予約・入金・記録をまとめる秘書アプリのLP。",
    score: { 完成度: 8, 実用性: 7, 独創性: 7 },
    comment: "「予約システムじゃない」と言い切るポジショニングが強い。アプリ画面のモックまで入った、資金調達にも使えるLP。" },
  { id: "shokunin", points: 79, camp: "7/30-31 ホリキャン", title: "しまの匠帳 ─ 職人検索", url: "https://twilight-rain-b764.197044tao.workers.dev/shokunin-search-sample.html", type: "app",
    desc: "奄美エリアの職人・業者を工種・地域・即対応可否で探せる検索サービス。",
    score: { 完成度: 7, 実用性: 9, 独創性: 7 },
    comment: "地域の「誰に頼めばいいか分からない」を解く、ローカルに刺さるサービス。電話・LINEにワンタップで繋がる導線も実用的。" },
  { id: "onsen", points: 71, camp: "8/8 オンライン", title: "雪見酒温泉 百選", url: "https://t-kawaberi.github.io/yukimizake-onsen/", type: "site",
    desc: "雪景色と地酒を楽しめる全国109の温泉を地方別に紹介するガイド。",
    score: { 完成度: 8, 実用性: 6, 独創性: 8 },
    comment: "“雪見酒”というニッチな切り口で109湯。夜空と月のトップ画面から、もう一杯やりたくなる。" },
  { id: "lure", points: 68, camp: "8/8 オンライン", title: "DEEP STRIKE LURES", url: "https://mitsutakakatou-ship.github.io/lure-fishing-shop/", type: "site",
    desc: "ハンドメイドルアーブランドのブランドサイト。",
    score: { 完成度: 8, 実用性: 6, 独創性: 6 },
    comment: "ブランドの世界観がしっかり立っている。シフトくんと合わせ1日で2本、振れ幅の大きさが光る。" },
  { id: "vesca", points: 67, camp: "8/8 オンライン", title: "CLEAR ─ 次世代決済端末", url: "https://toda-vesca.github.io/vesca-homepage/", type: "site",
    desc: "決済端末のサービスサイト。機能・導入の流れ・料金まで網羅。",
    score: { 完成度: 8, 実用性: 7, 独創性: 5 },
    comment: "数字で語るファーストビューと資料請求導線がBtoBの王道。実在のSaaSサイトと並べても遜色なし。" },
  { id: "adagency", points: 65, camp: "8/30 介護校", title: "SPARKWORKS 広告代理店HP", url: "https://ad-agency-homepage.vercel.app", type: "site",
    desc: "戦略からクリエイティブ・広告運用までを手がける広告代理店のコーポレートサイト。",
    score: { 完成度: 8, 実用性: 6, 独創性: 5 },
    comment: "ダーク基調にアクセントカラーが効いた、代理店らしいキレのあるデザイン。" },
  { id: "cafe", points: 64, camp: "9/13 対面", title: "Café Lumière", url: "https://kitajimataichi.github.io/cafe-lumiere/", type: "site",
    desc: "蔵前の自家焙煎カフェのサイト。物語・メニュー・ギャラリーまで。",
    score: { 完成度: 8, 実用性: 6, 独創性: 5 },
    comment: "写真と書体で“光が差し込む”空気感を再現。お店のオーナーに見せたら即採用されそう。" },
  { id: "ghpractice", points: 63, camp: "8/8 オンライン", title: "京都茶舗 松風園", url: "https://d-yoneda-a11y.github.io/github-practice/", type: "site",
    desc: "創業慶応四年の老舗お茶屋という設定のサイト。",
    score: { 完成度: 7, 実用性: 6, 独創性: 6 },
    comment: "「練習サイト」とは思えない和の品格。深緑と明朝体で老舗感を出す、トーン設計のお手本。" },
  { id: "tada", points: 62, camp: "8/8 オンライン", title: "JAPAN HOP!", url: "https://donbeidon3.github.io/HOME/", type: "site",
    desc: "20代向けの旅行スポットガイド。気分別カテゴリで探せる。",
    score: { 完成度: 7, 実用性: 6, 独創性: 6 },
    comment: "ポップな配色と“気分で選ぶ”フィルターで、若い世代にちゃんと向いている。" },
  { id: "amy", points: 61, camp: "8/18 対面", title: "マヤ暦鑑定 Amy", url: "https://amy-0008.github.io/study-pages/", type: "site",
    desc: "マヤ暦鑑定のサービスサイト。メニュー・プロフィール・お客様の声まで。",
    score: { 完成度: 7, 実用性: 7, 独創性: 5 },
    comment: "趣味を“予約が入るサイト”にまで仕上げた。夜空のような配色で世界観も◎。" },
  { id: "marche", points: 60, camp: "8/8 オンライン", title: "マルシェ出展者募集", url: "https://iedahitoshisky-felice.github.io/marche-vendor-2026/", type: "site",
    desc: "2026年11月開催のマルシェの出展者募集ページ。",
    score: { 完成度: 7, 実用性: 7, 独創性: 5 },
    comment: "募集対象・日程・概要が一目で分かる、実際の募集にそのまま使える実用ページ。" },
  { id: "crepe", points: 58, camp: "9/13 対面", title: "クレープハウス ポムドール", url: "https://nishiduka445.github.io/crepe-house-pomdor/", type: "site",
    desc: "手作り生地のクレープ専門店のサイト。",
    score: { 完成度: 6, 実用性: 6, 独創性: 6 },
    comment: "ビビッドなグラデーションで“甘くて楽しい”を全力表現。メニューの見せ方もお店らしい。" },
];
